#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
	
	# bsq-mes前端
	server {
        listen       82;
        server_name  0.0.0.0;
        charset utf-8;

        location / {
            root   ..\dist_mes;
			try_files $uri $uri/  /index.html;
            index  index.html index.htm;
        }
		
		location /prod-api/ {
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_pass http://127.0.0.1:8080/;
		}
		
		location /ureport {
			rewrite ^/(.*) http://127.0.0.1:8080/$1;
			proxy_pass http://127.0.0.1:8080/ureport;
		}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }      
    }
	
	# 标识解析——福州市电子二级节点代理
	server {
		listen       3000;
		server_name  0.0.0.0;
		location  /api/ {
			if ($request_method = 'OPTIONS') {
				add_header Access-Control-Allow-Origin '*';
				add_header Access-Control-Allow-Headers 'Content-Type,Authorization';
				add_header Access-Control-Allow-Methods 'DELETE,PUT,POST,GET,OPTIONS';
				return 204;
			}
			if ($request_method != 'OPTIONS') {
				add_header Access-Control-Allow-Origin '*' always;
			}
			
			#proxy_pass  https://www.fzcitln.cn;
			
		}
	}
	
	
}
