'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const baseline = require('../tools/ide-baseline.cjs')

function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'mes-ide-baseline-test-'))
  const workspace = path.join(root, 'ide-workspace', 'bsq_usr')
  fs.mkdirSync(path.join(workspace, 'src'), { recursive: true })
  fs.writeFileSync(path.join(workspace, 'src', 'code.js'), 'const original = 1\n')
  fs.writeFileSync(path.join(workspace, 'README.md'), 'current baseline')
  t.after(() => {
    const absolute = path.resolve(root)
    assert.equal(path.dirname(absolute), path.resolve(os.tmpdir()))
    assert.ok(path.basename(absolute).startsWith('mes-ide-baseline-test-'))
    fs.rmSync(absolute, { recursive: true, force: true })
  })
  return { root, workspace }
}
test('IDE reset restores edited and deleted files, removes additions, and keeps the fixed baseline', t => {
  const { root, workspace } = fixture(t)
  const captured = baseline.capture(root)
  fs.writeFileSync(path.join(workspace, 'src', 'code.js'), 'changed')
  fs.unlinkSync(path.join(workspace, 'README.md'))
  fs.mkdirSync(path.join(workspace, 'new-folder'))
  fs.writeFileSync(path.join(workspace, 'new-folder', 'new.js'), 'addition')
  const restored = baseline.restore(root)
  assert.equal(restored.id, captured.id)
  assert.equal(fs.readFileSync(path.join(workspace, 'src', 'code.js'), 'utf8'), 'const original = 1\n')
  assert.equal(fs.readFileSync(path.join(workspace, 'README.md'), 'utf8'), 'current baseline')
  assert.equal(fs.existsSync(path.join(workspace, 'new-folder')), false)
  assert.equal(baseline.restore(root).restored, 0)
  assert.throws(() => baseline.capture(root), /already exists/)
})
test('a damaged IDE baseline stops before deleting or changing current files', t => {
  const { root, workspace } = fixture(t)
  baseline.capture(root)
  fs.writeFileSync(path.join(root, 'ide-baseline', 'bsq_usr', 'README.md'), 'corrupted')
  fs.writeFileSync(path.join(workspace, 'new.js'), 'keep until valid restore')
  assert.throws(() => baseline.restore(root), /checksum mismatch/)
  assert.equal(fs.existsSync(path.join(workspace, 'new.js')), true)
})
test('IDE reset removes a junction without touching its external target', t => {
  const { root, workspace } = fixture(t)
  baseline.capture(root)
  const outside = path.join(root, 'outside')
  fs.mkdirSync(outside)
  fs.writeFileSync(path.join(outside, 'keep.txt'), 'untouched')
  fs.symlinkSync(outside, path.join(workspace, 'extra-link'), 'junction')
  baseline.restore(root)
  assert.equal(fs.readFileSync(path.join(outside, 'keep.txt'), 'utf8'), 'untouched')
  assert.equal(fs.existsSync(path.join(workspace, 'extra-link')), false)
})
